[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
    
    # Add any extra dependencies here

build_flags =
    -I../test
    -I../src
    -DUNITY_OUTPUT_COLOR

# Only build the bench/main.cpp as the entry point
src_dir = bench
